name: MinBZK Open Catalogi Workflow

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:              
      - name: Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@latest
        with:
          opencatalogi: true
      - name: Deploy Open Catalogi Github Page
        uses: OpenCatalogi/opencatalogi-action@latest